version: '3'

services:
  rocketmq-nameserver:
    image: apache/rocketmq:4.9.3
    container_name: rocketmq-nameserver
    hostname: rocketmq-nameserver
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "1"
    ports:
      - "9876:9876"
    command: "sh ./mqnamesrv"
    networks:
      - web

  rocketmq-broker:
    image: apache/rocketmq:4.9.3
    container_name: rocketmq-broker
    hostname: rocketmq-broker
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "1"
    ports:
      - "10911:10911"
    volumes:
      - "./store:/home/rocketmq/store"
      - "./conf/broker.conf:/opt/rocketmq/conf/broker.conf"
    command: "sh ./mqbroker -c /opt/rocketmq/conf/broker.conf -n rocketmq-nameserver:9876"
    depends_on:
      - rocketmq-nameserver
    networks:
      - web

  rocketmq-console:
    image : styletang/rocketmq-console-ng:1.0.0
    container_name: rocketmq-console
    hostname: rocketmq-console
    restart: "no"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "1"
    ports:
      - "8080:8080"
    environment:
      - "JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rocketmq-nameserver
      - rocketmq-broker
    networks:
      - web

networks:
  web:
    external:
      name: web